#!/bin/sh

echo "Installing RPi hardware config file ..."
cp root/boot/config.txt /boot
chown root:root /boot/config.txt
chmod 0755 /boot/config.txt

echo ""
echo "Expanding root filesystem size ..."
/usr/bin/raspi-config --expand-rootfs

echo ""
echo "Please reboot!!!!"

