#!/bin/sh

echo "Installing RPi hardware config file ..."
sudo cp root/boot/config.txt /boot
sudo chown root:root /boot/config.txt
sudo chmod 0755 /boot/config.txt

echo ""
echo "Expanding root filesystem size ..."
sudo /usr/bin/raspi-config --expand-rootfs

echo ""
echo "Please reboot!!!!"

