#!/bin/bash

OVERLAY=$PWD/root

set -e

# TODO: add dnsmasq to cache and redirect DNS to Google or OpenDNS
# TODO: randomize hostname?
# TODO: change pi username?
# TODO: change pi password
# TODO: allow changing of ssid, password, channel number, encryption type, in hostapd.conf
# TODO: remove unnecessary packages like X
# TODO: come up with a reset/power loss tolerant methdology (ro root for example)

##############################################################################
# Networking, DHCP server, access point
##############################################################################

apt-get install -y \
  hostapd isc-dhcp-server

# Configure DHCPd
TARGET=/etc/dhcp/dhcpd.conf
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET
TARGET=/etc/default/isc-dhcp-server
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET

# Set network interface config
TARGET=/etc/network/interfaces
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET

# hostapd config
TARGET=/etc/hostapd/hostapd.conf
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET
TARGET=/etc/default/hostapd
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET

# NAT
TARGET=/etc/sysctl.conf
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET
echo 1 > /proc/sys/net/ipv4/ip_forward
# NAT commands to generate config
# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
# iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
# View tables: iptables -t nat -S
# View tables: iptables -S
# iptables-save > /etc/iptables.ipv4.nat
TARGET=/etc/iptables.ipv4.nat
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET

# Update hostapd binary
TARGET=/usr/sbin/hostapd
rm -f $TARGET && ln -s $OVERLAY$TARGET $TARGET

# Enable daemons on startup
update-rc.d hostapd enable 
update-rc.d isc-dhcp-server enable


##############################################################################
# Database
##############################################################################

apt-get install -y \
  sqlite3 libdbi-perl libdbd-sqlite3-perl

./initialize_database

#####################
# APACHE WEB SERVER #
#####################
apt-get install -y apache2 php5 libapache2-mod-php5

#####################
# SQLITE3 for PHP5  #
#####################
apt-get install php5-sqlite



